-- Tabela de Bairros
CREATE TABLE IF NOT EXISTS `bairros` (
    `BAI_ID` INT(11) NOT NULL AUTO_INCREMENT,
    `BAI_NOME` VARCHAR(100) NOT NULL,
    `MUN_ID` INT(11) NOT NULL,
    `BAI_DATA_INCLUSAO` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `BAI_DATA_ATUALIZACAO` DATETIME NULL ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`BAI_ID`),
    KEY `idx_bairros_municipio` (`MUN_ID`),
    KEY `idx_bairros_nome` (`BAI_NOME`),
    CONSTRAINT `fk_bairros_municipios` FOREIGN KEY (`MUN_ID`) REFERENCES `municipios` (`MUN_ID`) ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE utf8mb4_general_ci;

-- Inserir alguns bairros de exemplo (principais bairros das capitais)
INSERT INTO `bairros` (`MUN_ID`, `BAI_NOME`) VALUES
-- São Paulo (MUN_ID = 1 - assumindo que São Paulo é o primeiro município inserido)
(1, 'Centro'),
(1, 'Vila Madalena'),
(1, 'Pinheiros'),
(1, 'Itaim Bibi'),
(1, 'Jardins'),
(1, 'Vila Olímpia'),
(1, 'Moema'),
(1, 'Brooklin'),
(1, 'Vila Nova Conceição'),
(1, 'Bela Vista'),
(1, 'Liberdade'),
(1, 'Consolação'),
(1, 'Higienópolis'),
(1, 'Vila Mariana'),
(1, 'Santo André'),
(1, 'Lapa'),
(1, 'Perdizes'),
(1, 'Vila Formosa'),
(1, 'Tatuapé'),

-- Rio de Janeiro (MUN_ID = 2)
(2, 'Centro'),
(2, 'Copacabana'),
(2, 'Ipanema'),
(2, 'Leblon'),
(2, 'Botafogo'),
(2, 'Flamengo'),
(2, 'Laranjeiras'),
(2, 'Catete'),
(2, 'Glória'),
(2, 'Santa Teresa'),
(2, 'Tijuca'),
(2, 'Maracanã'),
(2, 'Vila Isabel'),
(2, 'Grajaú'),
(2, 'Méier'),
(2, 'Engenho Novo'),
(2, 'Inhaúma'),
(2, 'Madureira'),
(2, 'Campo Grande'),

-- Belo Horizonte (MUN_ID = 3)
(3, 'Centro'),
(3, 'Savassi'),
(3, 'Funcionários'),
(3, 'Lourdes'),
(3, 'Santo Antônio'),
(3, 'Santa Efigênia'),
(3, 'Barro Preto'),
(3, 'Cidade Nova'),
(3, 'Floresta'),
(3, 'Santa Tereza'),
(3, 'Sagrada Família'),
(3, 'Padre Eustáquio'),
(3, 'Carlos Prates'),
(3, 'Coração Eucarístico'),
(3, 'Pampulha'),
(3, 'São Luís'),
(3, 'Caiçara'),
(3, 'Cidade Jardim'),
(3, 'Cidade Industrial'),

-- Salvador (MUN_ID = 4)
(4, 'Centro'),
(4, 'Pelourinho'),
(4, 'Barra'),
(4, 'Ondina'),
(4, 'Rio Vermelho'),
(4, 'Pituba'),
(4, 'Caminho das Árvores'),
(4, 'Costa Azul'),
(4, 'Stella Maris'),
(4, 'Itapuã'),
(4, 'Paripe'),
(4, 'Periperi'),
(4, 'Nova Brasília'),
(4, 'São Cristóvão'),
(4, 'Fazenda Grande'),
(4, 'Cajazeiras'),
(4, 'Valéria'),
(4, 'Liberdade'),
(4, 'São Caetano'),

-- Fortaleza (MUN_ID = 5)
(5, 'Centro'),
(5, 'Meireles'),
(5, 'Aldeota'),
(5, 'Praia de Iracema'),
(5, 'Varjota'),
(5, 'Dionísio Torres'),
(5, 'Cocó'),
(5, 'Papicu'),
(5, 'Sapiranga'),
(5, 'Conjunto Ceará'),
(5, 'Mondubim'),
(5, 'Parangaba'),
(5, 'Antônio Bezerra'),
(5, 'Bom Jardim'),
(5, 'Conjunto Esperança'),
(5, 'Granja Portugal'),
(5, 'Jardim América'),
(5, 'Messejana'),
(5, 'Montese'),
(5, 'Parque Araxá'),

-- Brasília (MUN_ID = 6)
(6, 'Plano Piloto'),
(6, 'Asa Norte'),
(6, 'Asa Sul'),
(6, 'Lago Sul'),
(6, 'Lago Norte'),
(6, 'Guará'),
(6, 'Taguatinga'),
(6, 'Ceilândia'),
(6, 'Samambaia'),
(6, 'Gama'),
(6, 'Santa Maria'),
(6, 'São Sebastião'),
(6, 'Sobradinho'),
(6, 'Planaltina'),
(6, 'Paranoá'),
(6, 'Itapoã'),
(6, 'Varjão'),
(6, 'Park Way'),
(6, 'Sudoeste'),

-- Curitiba (MUN_ID = 7)
(7, 'Centro'),
(7, 'Batel'),
(7, 'Bigorrilho'),
(7, 'Mercês'),
(7, 'Água Verde'),
(7, 'Vila Izabel'),
(7, 'Cristo Rei'),
(7, 'Santo Inácio'),
(7, 'Bacacheri'),
(7, 'Boa Vista'),
(7, 'Capão Raso'),
(7, 'Cidade Industrial'),
(7, 'Fazendinha'),
(7, 'Ganchinho'),
(7, 'Hauer'),
(7, 'Jardim Botânico'),
(7, 'Lamenha Pequena'),
(7, 'Mossunguê'),
(7, 'Novo Mundo'),
(7, 'Pilarzinho'),

-- Porto Alegre (MUN_ID = 8)
(8, 'Centro'),
(8, 'Cidade Baixa'),
(8, 'Bom Fim'),
(8, 'Moinhos de Vento'),
(8, 'Petrópolis'),
(8, 'Tristeza'),
(8, 'Vila Assunção'),
(8, 'Vila Conceição'),
(8, 'Vila Nova'),
(8, 'Cascata'),
(8, 'Cristal'),
(8, 'Glória'),
(8, 'Higienópolis'),
(8, 'Independência'),
(8, 'Jardim Botânico'),
(8, 'Jardim Carvalho'),
(8, 'Jardim do Salso'),
(8, 'Lami'),
(8, 'Lomba do Pinheiro'),

-- Recife (MUN_ID = 9)
(9, 'Centro'),
(9, 'Boa Viagem'),
(9, 'Pina'),
(9, 'Brasília Teimosa'),
(9, 'Piedade'),
(9, 'Jordão'),
(9, 'Imbiribeira'),
(9, 'Afogados'),
(9, 'Bongi'),
(9, 'Casa Amarela'),
(9, 'Casa Forte'),
(9, 'Cordeiro'),
(9, 'Derby'),
(9, 'Dois Irmãos'),
(9, 'Encruzilhada'),
(9, 'Espinheiro'),
(9, 'Graças'),
(9, 'Ilha do Leite'),
(9, 'Jaqueira'),

-- Belém (MUN_ID = 10)
(10, 'Centro'),
(10, 'Nazaré'),
(10, 'Batista Campos'),
(10, 'Umarizal'),
(10, 'Marco'),
(10, 'Pedreira'),
(10, 'Reduto'),
(10, 'São Brás'),
(10, 'Terra Firme'),
(10, 'Guamá'),
(10, 'Jurunas'),
(10, 'Condor'),
(10, 'Cremação'),
(10, 'Fátima'),
(10, 'Marambaia'),
(10, 'Montese'),
(10, 'Sacramenta'),
(10, 'Souza'),
(10, 'Telégrafo');

