-- Tabela de Telefones
CREATE TABLE IF NOT EXISTS `telefones` (
    `TEL_ID` INT(11) NOT NULL AUTO_INCREMENT,
    `PES_ID` INT(11) NOT NULL,
    `TEL_TIPO` ENUM('Celular','Comercial','Residencial','Whatsapp','Outros') NOT NULL,
    `TEL_DDD` VARCHAR(3) NOT NULL,
    `TEL_NUMERO` VARCHAR(12) NOT NULL,
    `TEL_OBSERVACAO` VARCHAR(255) NULL,
    `TEL_DATA_INCLUSAO` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `TEL_DATA_ATUALIZACAO` DATETIME NULL ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`TEL_ID`),
    KEY `idx_telefones_pessoa` (`PES_ID`),
    KEY `idx_telefones_tipo` (`TEL_TIPO`),
    CONSTRAINT `fk_telefones_pessoas` FOREIGN KEY (`PES_ID`) REFERENCES `pessoas` (`PES_ID`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;


