-- Tabela de Documentos
CREATE TABLE IF NOT EXISTS `documentos` (
    `DOC_ID` INT(11) NOT NULL AUTO_INCREMENT,
    `PES_ID` INT(11) NOT NULL,
    `DOC_TIPO_DOCUMENTO` VARCHAR(60) NOT NULL,
    `ENDEID` INT(11) NULL,
    `DOC_ORGAO_EXPEDIDOR` VARCHAR(60) NULL,
    `DOC_NUMERO` VARCHAR(60) NOT NULL,
    `DOC_NATUREZA_CONTRIBUINTE` ENUM('Contribuinte','Não Contribuinte') NULL,
    `DOC_DATA_INCLUSAO` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `DOC_DATA_ATUALIZACAO` DATETIME NULL ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`DOC_ID`),
    KEY `idx_documentos_pessoa` (`PES_ID`),
    KEY `idx_documentos_tipo` (`DOC_TIPO_DOCUMENTO`),
    KEY `idx_documentos_numero` (`DOC_NUMERO`),
    CONSTRAINT `fk_documentos_pessoas` FOREIGN KEY (`PES_ID`) REFERENCES `pessoas` (`PES_ID`) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT `fk_documentos_enderecos` FOREIGN KEY (`ENDEID`) REFERENCES `enderecos` (`END_ID`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;



