-- Tabela de Clientes (tipo de pessoa)
CREATE TABLE IF NOT EXISTS `clientes` (
    `CLN_ID` INT(11) NOT NULL AUTO_INCREMENT,
    `PES_ID` INT(11) NOT NULL,
    `CLN_LIMITE_CREDITO` DECIMAL(15,2) NULL,
    `CLN_SITUACAO` TINYINT(1) NOT NULL DEFAULT 1,
    `CLN_DATA_CADASTRO` DATETIME NULL,
    `CLN_LASTUPDATE` DATETIME NULL ON UPDATE CURRENT_TIMESTAMP,
    `CLN_COMPRAR_APRAZO` TINYINT(1) NOT NULL DEFAULT 0,
    `CLN_BLOQUEIO_FINANCEIRO` TINYINT(1) NOT NULL DEFAULT 0,
    `CLN_DIAS_CARENCIA` INT(11) NULL,
    `CLN_EMITIR_NFE` TINYINT(1) NOT NULL DEFAULT 0,
    `CLN_DATA_INCLUSAO` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `CLN_DATA_ALTERACAO` DATETIME NULL ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`CLN_ID`),
    UNIQUE KEY `uk_clientes_pes` (`PES_ID`),
    KEY `idx_clientes_situacao` (`CLN_SITUACAO`),
    CONSTRAINT `fk_clientes_pessoas` FOREIGN KEY (`PES_ID`) REFERENCES `pessoas` (`PES_ID`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;





