-- Tabela de Vendedores
CREATE TABLE IF NOT EXISTS `vendedores` (
    `VEN_ID` INT(11) NOT NULL AUTO_INCREMENT,
    `PES_ID` INT(11) NOT NULL,
    `VEN_PERCENTUAL_COMISSAO` DECIMAL(5,2) DEFAULT NULL COMMENT 'Percentual de comissão (ex: 5.50 = 5,5%)',
    `VEN_TIPO_COMISSAO` VARCHAR(20) DEFAULT NULL COMMENT 'Sobre Venda ou Sobre Lucro',
    `VEN_META_MENSAL` DECIMAL(10,2) DEFAULT NULL COMMENT 'Meta mensal de vendas',
    `VEN_SITUACAO` TINYINT(1) DEFAULT 1 COMMENT '1 = Ativo, 0 = Inativo',
    `VEN_DATA_CADASTRO` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `VEN_DATA_ATUALIZACAO` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`VEN_ID`),
    UNIQUE KEY `UK_PES_ID` (`PES_ID`),
    CONSTRAINT `FK_VENDEDORES_PES_ID` FOREIGN KEY (`PES_ID`) REFERENCES `pessoas` (`PES_ID`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci COMMENT='Tabela de vendedores';

