-- Tabela de relacionamento Clientes x Vendedores
CREATE TABLE IF NOT EXISTS `clientes_vendedores` (
    `CLV_ID` INT(11) NOT NULL AUTO_INCREMENT,
    `CLN_ID` INT(11) NOT NULL COMMENT 'ID do cliente',
    `VEN_ID` INT(11) NOT NULL COMMENT 'ID do vendedor',
    `CLV_PADRAO` TINYINT(1) DEFAULT 0 COMMENT '1 = Vendedor padrão, 0 = Vendedor permitido',
    `CLV_DATA_INCLUSAO` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `CLV_DATA_ATUALIZACAO` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`CLV_ID`),
    UNIQUE KEY `UK_CLIENTE_VENDEDOR` (`CLN_ID`, `VEN_ID`),
    CONSTRAINT `FK_CLV_CLIENTE` FOREIGN KEY (`CLN_ID`) REFERENCES `clientes` (`CLN_ID`) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT `FK_CLV_VENDEDOR` FOREIGN KEY (`VEN_ID`) REFERENCES `vendedores` (`VEN_ID`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci COMMENT='Relacionamento entre clientes e vendedores permitidos';

