-- Scripts para sincronizar AgilizePro com MapOS
-- Gerado em: 2026-01-25 02:23:37

ALTER TABLE `aliquotas` MODIFY COLUMN `ten_id` int(11) unsigned NOT NULL  ;
ALTER TABLE `anexos` MODIFY COLUMN `ten_id` int(11) unsigned NOT NULL  ;
ALTER TABLE `anotacoes_os` MODIFY COLUMN `ten_id` int(11) unsigned NOT NULL  ;
ALTER TABLE `bairros` MODIFY COLUMN `ten_id` int(11) unsigned NOT NULL  ;
ALTER TABLE `categorias` MODIFY COLUMN `ten_id` int(11) unsigned NOT NULL  ;
ALTER TABLE `certificados_digitais` MODIFY COLUMN `ten_id` int(11) unsigned NOT NULL  ;
ALTER TABLE `classificacao_fiscal` MODIFY COLUMN `ten_id` int(11) unsigned NOT NULL  ;
ALTER TABLE `clientes` MODIFY COLUMN `ten_id` int(11) unsigned NOT NULL  ;
ALTER TABLE `clientes_` MODIFY COLUMN `ten_id` int(11) unsigned NOT NULL  ;
ALTER TABLE `clientes_vendedores` MODIFY COLUMN `ten_id` int(11) unsigned NOT NULL  ;
ALTER TABLE `cobrancas` MODIFY COLUMN `ten_id` int(11) unsigned NOT NULL  ;
ALTER TABLE `configuracoes` MODIFY COLUMN `ten_id` int(11) unsigned NOT NULL  ;
ALTER TABLE `configuracoes_fiscais` MODIFY COLUMN `ten_id` int(11) unsigned NOT NULL  ;
ALTER TABLE `configuracoes_nfce` MODIFY COLUMN `ten_id` int(11) unsigned NOT NULL  ;
ALTER TABLE `configuracoes_nfe` MODIFY COLUMN `ten_id` int(11) unsigned NOT NULL  ;
ALTER TABLE `contas` MODIFY COLUMN `ten_id` int(11) unsigned NOT NULL  ;
ALTER TABLE `contratos` MODIFY COLUMN `ten_id` int(11) unsigned NOT NULL  ;
ALTER TABLE `documentos` MODIFY COLUMN `ten_id` int(11) unsigned NOT NULL  ;
ALTER TABLE `documentos_faturados` MODIFY COLUMN `ten_id` int(11) unsigned NOT NULL  ;
ALTER TABLE `email_queue` ADD COLUMN `ten_id` int(11) unsigned NOT NULL  ;
ALTER TABLE `emails` ADD COLUMN `ten_id` int(11) unsigned NOT NULL  ;
ALTER TABLE `emitente` ADD COLUMN `ten_id` int(11) unsigned NOT NULL  ;
ALTER TABLE `empresas` ADD COLUMN `ten_id` int(11) unsigned NOT NULL  ;
ALTER TABLE `enderecos` ADD COLUMN `ten_id` int(11) unsigned NOT NULL  ;
ALTER TABLE `equipamentos` ADD COLUMN `ten_id` int(11) unsigned NOT NULL  ;
ALTER TABLE `equipamentos_os` ADD COLUMN `ten_id` int(11) unsigned NOT NULL  ;
ALTER TABLE `estados` ADD COLUMN `ten_id` int(11) unsigned NOT NULL  ;
ALTER TABLE `faturamento_entrada` ADD COLUMN `ten_id` int(11) unsigned NOT NULL  ;
ALTER TABLE `faturamento_entrada_itens` ADD COLUMN `ten_id` int(11) unsigned NOT NULL  ;
ALTER TABLE `fornecedores` ADD COLUMN `ten_id` int(11) unsigned NOT NULL  ;
ALTER TABLE `garantias` ADD COLUMN `ten_id` int(11) unsigned NOT NULL  ;
ALTER TABLE `itens_de_vendas` ADD COLUMN `ten_id` int(11) unsigned NOT NULL  ;
ALTER TABLE `itens_faturados` ADD COLUMN `ten_id` int(11) unsigned NOT NULL  ;
ALTER TABLE `itens_pedido` ADD COLUMN `ten_id` int(11) unsigned NOT NULL  ;
ALTER TABLE `lancamentos` ADD COLUMN `ten_id` int(11) unsigned NOT NULL  ;
ALTER TABLE `logs` ADD COLUMN `ten_id` int(11) unsigned NOT NULL  ;
ALTER TABLE `marcas` ADD COLUMN `ten_id` int(11) unsigned NOT NULL  ;
ALTER TABLE `marcas_equipamentos` ADD COLUMN `ten_id` int(11) unsigned NOT NULL  ;
ALTER TABLE `municipios` ADD COLUMN `ten_id` int(11) unsigned NOT NULL  ;
ALTER TABLE `ncms` ADD COLUMN `ten_id` int(11) unsigned NOT NULL  ;
ALTER TABLE `nfe_certificates` ADD COLUMN `ten_id` int(11) unsigned NOT NULL  ;
ALTER TABLE `nfe_documentos` ADD COLUMN `ten_id` int(11) unsigned NOT NULL  ;
ALTER TABLE `nfe_emitidas` ADD COLUMN `ten_id` int(11) unsigned NOT NULL  ;
ALTER TABLE `nfecom_capa` ADD COLUMN `NFC_V_BC_ICMS` decimal(15,2) NOT NULL DEFAULT '0.00' ;
ALTER TABLE `nfecom_capa` ADD COLUMN `NFC_V_ICMS` decimal(15,2) NOT NULL DEFAULT '0.00' ;
ALTER TABLE `nfecom_capa` ADD COLUMN `NFC_V_ICMS_DESON` decimal(15,2) NOT NULL DEFAULT '0.00' ;
ALTER TABLE `nfecom_capa` ADD COLUMN `NFC_V_FCP` decimal(15,2) NOT NULL DEFAULT '0.00' ;
ALTER TABLE `nfecom_capa` ADD COLUMN `ten_id` int(11) unsigned NOT NULL  ;
ALTER TABLE `nfecom_itens` ADD COLUMN `NFI_CSOSN` varchar(3) NULL  ;
ALTER TABLE `nfecom_itens` ADD COLUMN `NFI_V_BC_ICMS` decimal(15,2) NOT NULL DEFAULT '0.00' ;
ALTER TABLE `nfecom_itens` ADD COLUMN `NFI_P_ICMS` decimal(5,2) NOT NULL DEFAULT '0.00' ;
ALTER TABLE `nfecom_itens` ADD COLUMN `NFI_V_ICMS` decimal(15,2) NOT NULL DEFAULT '0.00' ;
ALTER TABLE `nfecom_itens` ADD COLUMN `NFI_V_ICMS_DESON` decimal(15,2) NOT NULL DEFAULT '0.00' ;
ALTER TABLE `nfecom_itens` ADD COLUMN `NFI_MOT_DES_ICMS` varchar(2) NULL  ;
ALTER TABLE `nfecom_itens` ADD COLUMN `NFI_V_BC_ICMS_ST` decimal(15,2) NOT NULL DEFAULT '0.00' ;
ALTER TABLE `nfecom_itens` ADD COLUMN `NFI_P_ICMS_ST` decimal(5,2) NOT NULL DEFAULT '0.00' ;
ALTER TABLE `nfecom_itens` ADD COLUMN `NFI_V_ICMS_ST` decimal(15,2) NOT NULL DEFAULT '0.00' ;
ALTER TABLE `nfecom_itens` ADD COLUMN `NFI_V_BC_ST_RET` decimal(15,2) NOT NULL DEFAULT '0.00' ;
ALTER TABLE `nfecom_itens` ADD COLUMN `NFI_V_ICMS_ST_RET` decimal(15,2) NOT NULL DEFAULT '0.00' ;
ALTER TABLE `nfecom_itens` ADD COLUMN `NFI_P_ST` decimal(5,2) NOT NULL DEFAULT '0.00' ;
ALTER TABLE `nfecom_itens` ADD COLUMN `NFI_V_ICMS_SUBST` decimal(15,2) NOT NULL DEFAULT '0.00' ;
ALTER TABLE `nfecom_itens` ADD COLUMN `NFI_V_BC_FCP` decimal(15,2) NOT NULL DEFAULT '0.00' ;
ALTER TABLE `nfecom_itens` ADD COLUMN `NFI_P_FCP` decimal(5,2) NOT NULL DEFAULT '0.00' ;
ALTER TABLE `nfecom_itens` ADD COLUMN `NFI_V_FCP` decimal(15,2) NOT NULL DEFAULT '0.00' ;
ALTER TABLE `nfecom_itens` ADD COLUMN `NFI_V_FCP_ST` decimal(15,2) NOT NULL DEFAULT '0.00' ;
ALTER TABLE `nfecom_itens` ADD COLUMN `NFI_V_FCP_ST_RET` decimal(15,2) NOT NULL DEFAULT '0.00' ;
ALTER TABLE `nfecom_itens` ADD COLUMN `ten_id` int(11) unsigned NOT NULL  ;
ALTER TABLE `operacao_comercial` ADD COLUMN `ten_id` int(11) unsigned NOT NULL  ;
ALTER TABLE `operacao_comercial_old` ADD COLUMN `ten_id` int(11) unsigned NOT NULL  ;
ALTER TABLE `ordem_servico` ADD COLUMN `ten_id` int(11) unsigned NOT NULL  ;
ALTER TABLE `os` ADD COLUMN `ten_id` int(11) unsigned NOT NULL  ;
ALTER TABLE `pedidos_compra` ADD COLUMN `ten_id` int(11) unsigned NOT NULL  ;
ALTER TABLE `permissoes` ADD COLUMN `ten_id` int(11) unsigned NOT NULL  ;
ALTER TABLE `pessoas` ADD COLUMN `ten_id` int(11) unsigned NOT NULL  ;
ALTER TABLE `pessoas` MODIFY COLUMN `PES_CPFCNPJ` varchar(20) NOT NULL  ;
ALTER TABLE `produtos` ADD COLUMN `PRO_FINALIDADE` varchar(30) NULL  ;
ALTER TABLE `produtos` ADD COLUMN `ten_id` int(11) unsigned NOT NULL  ;
ALTER TABLE `produtos_os` ADD COLUMN `ten_id` int(11) unsigned NOT NULL  ;
ALTER TABLE `protocolos` ADD COLUMN `ten_id` int(11) unsigned NOT NULL  ;
ALTER TABLE `resets_de_senha` ADD COLUMN `ten_id` int(11) unsigned NOT NULL  ;
ALTER TABLE `servicos` ADD COLUMN `ten_id` int(11) unsigned NOT NULL  ;
ALTER TABLE `servicos_os` ADD COLUMN `ten_id` int(11) unsigned NOT NULL  ;
ALTER TABLE `telefones` ADD COLUMN `ten_id` int(11) unsigned NOT NULL  ;
ALTER TABLE `tipos_clientes` ADD COLUMN `ten_id` int(11) unsigned NOT NULL  ;
ALTER TABLE `tipos_pessoa` ADD COLUMN `ten_id` int(11) unsigned NOT NULL  ;
ALTER TABLE `tributacao_estadual` ADD COLUMN `ten_id` int(11) unsigned NOT NULL  ;
ALTER TABLE `tributacao_estadual` MODIFY COLUMN `tbe_tipo_tributacao` enum('ICMS Normal','ST','Serviço') NOT NULL  ;
ALTER TABLE `tributacao_federal` ADD COLUMN `ten_id` int(11) unsigned NOT NULL  ;
ALTER TABLE `tributacao_produto` ADD COLUMN `ten_id` int(11) unsigned NOT NULL  ;
ALTER TABLE `tributacao_produto` MODIFY COLUMN `regime_fiscal_tributario` enum('ICMS Normal (Tributado)','Substituição Tributária') NOT NULL  ;
ALTER TABLE `usuarios` ADD COLUMN `ten_id` int(11) unsigned NOT NULL  ;
ALTER TABLE `vendas` ADD COLUMN `ten_id` int(11) unsigned NOT NULL  ;
ALTER TABLE `vendedores` ADD COLUMN `ten_id` int(11) unsigned NOT NULL  ;