<?php

defined('BASEPATH') or exit('No direct script access allowed');

class AliquotasSeeder extends CI_Seeder
{
    public function run()
    {
        $data = [
            [
                'cst' => '00',
                'destinacao' => 'INTERNA',
                'natureza_contribuinte' => 'inscrito',
                'aliquota_icms' => 18.00,
                'aliquota_icms_st' => 18.00,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'cst' => '00',
                'destinacao' => 'INTERNA',
                'natureza_contribuinte' => 'nao_inscrito',
                'aliquota_icms' => 18.00,
                'aliquota_icms_st' => 18.00,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'cst' => '10',
                'destinacao' => 'INTERNA',
                'natureza_contribuinte' => 'inscrito',
                'aliquota_icms' => 18.00,
                'aliquota_icms_st' => 18.00,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'cst' => '10',
                'destinacao' => 'INTERNA',
                'natureza_contribuinte' => 'nao_inscrito',
                'aliquota_icms' => 18.00,
                'aliquota_icms_st' => 18.00,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'cst' => '20',
                'destinacao' => 'INTERNA',
                'natureza_contribuinte' => 'inscrito',
                'aliquota_icms' => 18.00,
                'aliquota_icms_st' => 18.00,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'cst' => '20',
                'destinacao' => 'INTERNA',
                'natureza_contribuinte' => 'nao_inscrito',
                'aliquota_icms' => 18.00,
                'aliquota_icms_st' => 18.00,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'cst' => '30',
                'destinacao' => 'INTERNA',
                'natureza_contribuinte' => 'inscrito',
                'aliquota_icms' => 18.00,
                'aliquota_icms_st' => 18.00,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'cst' => '30',
                'destinacao' => 'INTERNA',
                'natureza_contribuinte' => 'nao_inscrito',
                'aliquota_icms' => 18.00,
                'aliquota_icms_st' => 18.00,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'cst' => '40',
                'destinacao' => 'INTERNA',
                'natureza_contribuinte' => 'inscrito',
                'aliquota_icms' => 0.00,
                'aliquota_icms_st' => 0.00,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'cst' => '40',
                'destinacao' => 'INTERNA',
                'natureza_contribuinte' => 'nao_inscrito',
                'aliquota_icms' => 0.00,
                'aliquota_icms_st' => 0.00,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'cst' => '41',
                'destinacao' => 'INTERNA',
                'natureza_contribuinte' => 'inscrito',
                'aliquota_icms' => 0.00,
                'aliquota_icms_st' => 0.00,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'cst' => '41',
                'destinacao' => 'INTERNA',
                'natureza_contribuinte' => 'nao_inscrito',
                'aliquota_icms' => 0.00,
                'aliquota_icms_st' => 0.00,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'cst' => '50',
                'destinacao' => 'INTERNA',
                'natureza_contribuinte' => 'inscrito',
                'aliquota_icms' => 0.00,
                'aliquota_icms_st' => 0.00,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'cst' => '50',
                'destinacao' => 'INTERNA',
                'natureza_contribuinte' => 'nao_inscrito',
                'aliquota_icms' => 0.00,
                'aliquota_icms_st' => 0.00,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'cst' => '51',
                'destinacao' => 'INTERNA',
                'natureza_contribuinte' => 'inscrito',
                'aliquota_icms' => 0.00,
                'aliquota_icms_st' => 0.00,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'cst' => '51',
                'destinacao' => 'INTERNA',
                'natureza_contribuinte' => 'nao_inscrito',
                'aliquota_icms' => 0.00,
                'aliquota_icms_st' => 0.00,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'cst' => '60',
                'destinacao' => 'INTERNA',
                'natureza_contribuinte' => 'inscrito',
                'aliquota_icms' => 18.00,
                'aliquota_icms_st' => 18.00,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'cst' => '60',
                'destinacao' => 'INTERNA',
                'natureza_contribuinte' => 'nao_inscrito',
                'aliquota_icms' => 18.00,
                'aliquota_icms_st' => 18.00,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'cst' => '70',
                'destinacao' => 'INTERNA',
                'natureza_contribuinte' => 'inscrito',
                'aliquota_icms' => 18.00,
                'aliquota_icms_st' => 18.00,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'cst' => '70',
                'destinacao' => 'INTERNA',
                'natureza_contribuinte' => 'nao_inscrito',
                'aliquota_icms' => 18.00,
                'aliquota_icms_st' => 18.00,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'cst' => '90',
                'destinacao' => 'INTERNA',
                'natureza_contribuinte' => 'inscrito',
                'aliquota_icms' => 18.00,
                'aliquota_icms_st' => 18.00,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'cst' => '90',
                'destinacao' => 'INTERNA',
                'natureza_contribuinte' => 'nao_inscrito',
                'aliquota_icms' => 18.00,
                'aliquota_icms_st' => 18.00,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
        ];

        $this->db->insert_batch('aliquotas', $data);
    }
} 